### ISSUE TITLE
compile 'io.saeid:fab-loading:0.6.0' not valid adress

### ISSUE THREAD

**Issue by serkandyck** [smasoumi/FAB-Loading#1]
Gradle cant build this

**Comment by SaeedMasoumi** [comment]
Did you add `jcenter()` into your build.gradle? it's available on jcenter 
https://bintray.com/bintray/jcenter?filterByPkgName=fab-loading

If still you have problem add my repo

```
repositories { maven { url "http://dl.bintray.com/smasoumi/maven" } }
```

**Comment by serkandyck** [comment]
jcenter() fixed error thnx
