### ISSUE TITLE
Fab loading animation isn't shown on lower api's such as 19

### ISSUE THREAD

**Issue by ahmetcj4** [smasoumi/FAB-Loading#3]

**Comment by SaeedMasoumi** [comment]
@ahmetcj4 I've tested it on api 16 and it's fine. Are you sure?

**Comment by ahmetcj4** [comment]
@SaeedMasoumi you are right. I cloned this library and run the sample program it works perfectly fine. However, when I import the project using gradle and use it in my project its animation isn't shown

**Comment by SaeedMasoumi** [comment]
@ahmetcj4 Also the sample project use gradle https://github.com/SaeedMasoumi/FAB-Loading/blob/master/sample/build.gradle#L25

**Comment by ahmetcj4** [comment]
I checked and I found that repeat attribute in xml working in wrong way on lower api's

**Comment by ahmetcj4** [comment]
@SaeedMasoumi when I use setRepeat function it works perfectly however when I set it using xml attribute then it shows only images without animating them

**Comment by SaeedMasoumi** [comment]
@ahmetcj4 Well, I changed that repeat attribute in sample project (https://github.com/SaeedMasoumi/FAB-Loading/blob/master/sample/src/main/res/layout/activity_main.xml#L45) to a greater number and it worked properly (tested on api 16 again)

**Comment by ahmetcj4** [comment]
I will check it out thanks
